version: '3'
services:
  poc:
    build: .
    restart: always
    ports:
      - 80:9999
      - 443:9999
      - 9999:9999
    environment:
      - NODE_ENV=production
      - DOMAIN=margarita.lopezjuri.com
      - HOST=0.0.0.0
      - PORT=9999
    env_file:
      - .env
